/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TMPanelMOB.java
 *
 * Created on Feb 22, 2012, 12:21:01 AM
 */
package SMS;

import Mobile.*;
import APX.PHController;
import APX.PHMain;
import PHilae.EILogin;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.BalloonTipStyle;
import net.java.balloontip.styles.EdgedBalloonStyle;
import net.java.balloontip.utils.FadingUtils;
import net.java.balloontip.utils.TimingUtils;

/**
 *
 * @author Pecherk
 */
public class SMSConfigPanel extends javax.swing.JPanel
{

    private JDialog smsAlertTemplateDialog = null;
    private final TDClientMOB tDClient = new TDClientMOB();
    private SMSTemplate sMSTemplate = new SMSTemplate();

    /**
     * Creates new form EITerminalMOB
     */
    public SMSConfigPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        templatePopupMenu = new javax.swing.JPopupMenu();
        acctNoPHMenuItem = new javax.swing.JMenuItem();
        custNamePHMenuItem = new javax.swing.JMenuItem();
        currencyPHMenuItem = new javax.swing.JMenuItem();
        amountPHMenuItem = new javax.swing.JMenuItem();
        chargePHMenuItem = new javax.swing.JMenuItem();
        descriptionPHMenuItem = new javax.swing.JMenuItem();
        datePHMenuItem = new javax.swing.JMenuItem();
        txnOriginatorPHMenuItem = new javax.swing.JMenuItem();
        daysPHMenuItem = new javax.swing.JMenuItem();
        accessCodePHMenuItem = new javax.swing.JMenuItem();
        pinPHMenuItem = new javax.swing.JMenuItem();
        balancePHMenuItem = new javax.swing.JMenuItem();
        dueDatePHMenuItem = new javax.swing.JMenuItem();
        repayAmountPHMenuItem = new javax.swing.JMenuItem();
        unpaidAmountPHMenuItem = new javax.swing.JMenuItem();
        contraAcctNoPHMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        currenciesPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        chargeLedgerField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chargeAmtField = new javax.swing.JTextField();
        chargeDescField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        taxLedgerField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        taxPercField = new javax.swing.JTextField();
        taxDescField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        taxAmtField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        moduleBox = new javax.swing.JComboBox();
        chargableBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        currencyBox = new javax.swing.JComboBox();
        dateModifiedField = new javax.swing.JTextField();
        modifiedByField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        statusBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        templateIDField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        alertType = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        insertPHButton = new javax.swing.JButton();
        templateScroller = new javax.swing.JScrollPane();
        messageTemplateArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        cancelButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        saveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        findBox = new javax.swing.JComboBox();
        findField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        terminalsScroller = new javax.swing.JScrollPane();
        alertTypeTree = new javax.swing.JTree();
        jSeparator3 = new javax.swing.JSeparator();

        templatePopupMenu.setLabel("Variable Fields");

        acctNoPHMenuItem.setText("Account Number");
        acctNoPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                acctNoPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(acctNoPHMenuItem);

        custNamePHMenuItem.setText("Customer Name");
        custNamePHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                custNamePHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(custNamePHMenuItem);

        currencyPHMenuItem.setText("Transaction Currency");
        currencyPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                currencyPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(currencyPHMenuItem);

        amountPHMenuItem.setText("Transaction Amount");
        amountPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                amountPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(amountPHMenuItem);

        chargePHMenuItem.setText("Transaction Charge");
        chargePHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chargePHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(chargePHMenuItem);

        descriptionPHMenuItem.setText("Transaction Description");
        descriptionPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                descriptionPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(descriptionPHMenuItem);

        datePHMenuItem.setText("Transaction Date");
        datePHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                datePHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(datePHMenuItem);

        txnOriginatorPHMenuItem.setText("Transaction Originator");
        txnOriginatorPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txnOriginatorPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(txnOriginatorPHMenuItem);

        daysPHMenuItem.setText("Days Due or Days Past");
        daysPHMenuItem.setToolTipText("");
        daysPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                daysPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(daysPHMenuItem);

        accessCodePHMenuItem.setText("Access Code");
        accessCodePHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                accessCodePHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(accessCodePHMenuItem);

        pinPHMenuItem.setText("Mobile PIN");
        pinPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pinPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(pinPHMenuItem);

        balancePHMenuItem.setText("Cleared Balance");
        balancePHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                balancePHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(balancePHMenuItem);

        dueDatePHMenuItem.setText("Loan Due Date");
        dueDatePHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dueDatePHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(dueDatePHMenuItem);

        repayAmountPHMenuItem.setText("Repayment Amount");
        repayAmountPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                repayAmountPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(repayAmountPHMenuItem);

        unpaidAmountPHMenuItem.setText("Unpaid Amount");
        unpaidAmountPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                unpaidAmountPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(unpaidAmountPHMenuItem);

        contraAcctNoPHMenuItem.setText("Contra Account Number");
        contraAcctNoPHMenuItem.setToolTipText("");
        contraAcctNoPHMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                contraAcctNoPHMenuItemActionPerformed(evt);
            }
        });
        templatePopupMenu.add(contraAcctNoPHMenuItem);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));

        currenciesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray), "Accounts"));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));

        chargeLedgerField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                chargeLedgerFieldFocusLost(evt);
            }
        });

        jLabel3.setText("Charge Ledger");

        jLabel4.setText("Charge Desc");

        jLabel6.setText("Charge Amt");

        chargeAmtField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                chargeAmtFieldFocusLost(evt);
            }
        });

        chargeDescField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                chargeDescFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chargeLedgerField, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(chargeDescField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(chargeAmtField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(chargeAmtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chargeLedgerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chargeDescField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));

        taxLedgerField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                taxLedgerFieldFocusLost(evt);
            }
        });

        jLabel13.setText("Tax Ledger");

        jLabel14.setText("Tax Desc");

        jLabel16.setText("Tax %age");

        taxPercField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                taxPercFieldFocusLost(evt);
            }
        });

        taxDescField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                taxDescFieldFocusLost(evt);
            }
        });

        jLabel15.setText("Tax Amt");

        taxAmtField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                taxAmtFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taxLedgerField)
                    .addComponent(taxDescField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxPercField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxAmtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(taxLedgerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxDescField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(taxPercField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(taxAmtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout currenciesPanelLayout = new javax.swing.GroupLayout(currenciesPanel);
        currenciesPanel.setLayout(currenciesPanelLayout);
        currenciesPanelLayout.setHorizontalGroup(
            currenciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        currenciesPanelLayout.setVerticalGroup(
            currenciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currenciesPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Template Details"));

        moduleBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select --", "MOB", "POS" }));

        jLabel12.setText("Chargable");

        currencyBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ZMW", "USD" }));
        currencyBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                currencyBoxActionPerformed(evt);
            }
        });

        dateModifiedField.setEditable(false);
        dateModifiedField.setForeground(new java.awt.Color(51, 102, 255));

        modifiedByField.setEditable(false);
        modifiedByField.setForeground(new java.awt.Color(51, 102, 255));

        jLabel11.setText("Date Modified");

        statusBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Closed" }));

        jLabel8.setText("Last Modified By");

        jLabel5.setText("Currency");

        templateIDField.setEditable(false);
        templateIDField.setBackground(new java.awt.Color(204, 204, 255));
        templateIDField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                templateIDFieldFocusLost(evt);
            }
        });

        jLabel7.setText("Status");

        jLabel2.setText("Module");

        jLabel10.setText("Template ID");

        jLabel17.setText("Alert Type");

        alertType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select --", "DR", "CR", "TFR", "TFR2", "ENQ", "BRD" }));
        alertType.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                alertTypeItemStateChanged(evt);
            }
        });
        alertType.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                alertTypePropertyChange(evt);
            }
        });

        jLabel18.setText("Description");

        descriptionField.setEditable(false);
        descriptionField.setBackground(new java.awt.Color(255, 255, 255));
        descriptionField.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alertType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(templateIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chargableBox))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(moduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(dateModifiedField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifiedByField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alertType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel10)
                        .addComponent(templateIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(chargableBox))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(currencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(moduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dateModifiedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifiedByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Message Template");

        insertPHButton.setText("Insert Field");
        insertPHButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                insertPHButtonActionPerformed(evt);
            }
        });

        messageTemplateArea.setColumns(20);
        messageTemplateArea.setForeground(new java.awt.Color(51, 102, 255));
        messageTemplateArea.setLineWrap(true);
        messageTemplateArea.setRows(5);
        messageTemplateArea.setToolTipText("Right-click on template text area or click the <Insert Field> button to insert a variable field.");
        messageTemplateArea.setWrapStyleWord(true);
        messageTemplateArea.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                messageTemplateAreaFocusLost(evt);
            }
        });
        messageTemplateArea.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                messageTemplateAreaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                messageTemplateAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                messageTemplateAreaMouseReleased(evt);
            }
        });
        templateScroller.setViewportView(messageTemplateArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(templateScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertPHButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(templateScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(insertPHButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(currenciesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currenciesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.white);

        jLabel9.setText("Find By");

        findBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alert" }));
        findBox.setFocusable(false);

        findField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                findFieldActionPerformed(evt);
            }
        });

        findButton.setBackground(java.awt.Color.white);
        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        findButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                findButtonActionPerformed(evt);
            }
        });

        terminalsScroller.setBorder(null);

        alertTypeTree.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Alert Type");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Add Alert");
        treeNode1.add(treeNode2);
        alertTypeTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        alertTypeTree.setCellRenderer(new Mobile.TRendererMOB());
        alertTypeTree.setRootVisible(false);
        alertTypeTree.setShowsRootHandles(true);
        alertTypeTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener()
        {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt)
            {
                alertTypeTreeValueChanged(evt);
            }
        });
        terminalsScroller.setViewportView(alertTypeTree);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(terminalsScroller)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(findBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminalsScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(595, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(cancelButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alertTypeTreeValueChanged(javax.swing.event.TreeSelectionEvent evt)//GEN-FIRST:event_alertTypeTreeValueChanged
    {//GEN-HEADEREND:event_alertTypeTreeValueChanged
        // TODO add your handling code here:
        displayAlert();
}//GEN-LAST:event_alertTypeTreeValueChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        hideAlertDialog();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void displayAlert()
    {
        DefaultMutableTreeNode selectedAlertNode = (DefaultMutableTreeNode) alertTypeTree.getLastSelectedPathComponent();
        if (selectedAlertNode != null)
        {
            Object selectedNode = selectedAlertNode.getUserObject();
            if ("Add Alert".equals(selectedNode))
            {
                sMSTemplate = new SMSTemplate();
                templateIDField.setEditable(true);
                templateIDField.setText("");
                messageTemplateArea.setText("");
                moduleBox.setSelectedIndex(0);
                statusBox.setSelectedIndex(0);
                modifiedByField.setText("");
                dateModifiedField.setText("");
                currencyBox.setSelectedIndex(0);
                chargeLedgerField.setText("");
                chargeDescField.setText("");
                chargeAmtField.setText("");
                taxLedgerField.setText("");
                taxDescField.setText("");
                taxAmtField.setText("");
                taxPercField.setText("");
                descriptionField.setText("");
                alertType.setSelectedIndex(0);
                chargableBox.setSelected(false);
                saveButton.setEnabled(true);
                saveButton.setText("Save");

            }
            else if (selectedNode instanceof SMSTemplate)
            {
                sMSTemplate = (SMSTemplate) selectedNode;
                templateIDField.setEditable(false);
                templateIDField.setText(sMSTemplate.getTemplateId());
                messageTemplateArea.setText(sMSTemplate.getTemplateMsg());
                moduleBox.setSelectedItem(sMSTemplate.getModule());
                statusBox.setSelectedItem(sMSTemplate.getStatus());
                modifiedByField.setText(sMSTemplate.getModifiedBy());
                currencyBox.setSelectedItem(sMSTemplate.getCurrency());
                chargeLedgerField.setText(sMSTemplate.getChargeLedger());
                chargeDescField.setText(sMSTemplate.getChargeDesc());
                chargeAmtField.setText(String.valueOf(sMSTemplate.getChargeAmt()));
                taxLedgerField.setText(sMSTemplate.getTaxledger());
                taxDescField.setText(sMSTemplate.getTaxDesc());
                taxAmtField.setText(String.valueOf(sMSTemplate.getTaxAmt()));
                taxPercField.setText(String.valueOf(sMSTemplate.getTaxPerc()));
                descriptionField.setText(sMSTemplate.getDescription());
                alertType.setSelectedItem(sMSTemplate.getAlertType());
                if (sMSTemplate.getIsChargable().equals("Y"))
                {
                    chargableBox.setSelected(true);
                }
                else
                {
                    chargableBox.setSelected(false);
                }

                dateModifiedField.setText(new SimpleDateFormat("EEE, d MMM yyyy HH:mm:ss a").format(sMSTemplate.getDateModified()));
                saveButton.setText("Update");
                saveButton.setEnabled(true);
            }
        }
    }

    public void showSmsTemplateDialog()
    {
        setAlertTree();
        alertTypeTree.setSelectionRow(0);
        if (smsAlertTemplateDialog == null)
        {
            smsAlertTemplateDialog = new JDialog(PHMain.phFrame, PHController.MobModule + " SMS Alert");
            smsAlertTemplateDialog.setContentPane(this);
            smsAlertTemplateDialog.pack();
            smsAlertTemplateDialog.setResizable(false);
        }

        smsAlertTemplateDialog.setIconImage(PHMain.phFrame.getIconImage());
        smsAlertTemplateDialog.setLocationRelativeTo(PHMain.phFrame);
        smsAlertTemplateDialog.setVisible(true);
    }

    public void hideAlertDialog()
    {
        smsAlertTemplateDialog.setVisible(false);
        tDClient.dispose();
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (alertType.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "Alert Type required.");
        }
        else if (templateIDField.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Template Id required.");
        }
        else if (messageTemplateArea.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Description required.");
        }
        else if (moduleBox.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "Module required.");
        }
        else if (chargeAmtField.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "charge required.");
        }
        else if (chargeLedgerField.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Account Number required.");
        } else if (descriptionField.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Description required.");
        }
        else
        {
            sMSTemplate.setTemplateId(templateIDField.getText().trim());
            sMSTemplate.setCurrency(currencyBox.getSelectedItem().toString());

            sMSTemplate.setTemplateMsg(messageTemplateArea.getText().trim().replaceAll("'", "''"));
            sMSTemplate.setModule(moduleBox.getSelectedItem().toString());

            sMSTemplate.setStatus(statusBox.getSelectedItem().toString());
            sMSTemplate.setModifiedBy(EILogin.getAdminName());

            sMSTemplate.setDateModified(new Date());
            sMSTemplate.setChargeLedger(chargeLedgerField.getText().trim());

            sMSTemplate.setChargeDesc(chargeDescField.getText().trim());
            sMSTemplate.setChargeAmt(new BigDecimal(chargeAmtField.getText()));

            sMSTemplate.setTaxledger(taxLedgerField.getText().trim());
            sMSTemplate.setTaxDesc(taxDescField.getText().trim());

            sMSTemplate.setTaxAmt(new BigDecimal(taxAmtField.getText()));
            sMSTemplate.setTaxPerc(new BigDecimal(taxPercField.getText()));

            sMSTemplate.setIsChargable(chargableBox.isSelected() ? "Y" : "N");
            sMSTemplate.setCurrency(currencyBox.getSelectedItem().toString());
            
            sMSTemplate.setAlertType(alertType.getSelectedItem().toString());
            sMSTemplate.setDescription(descriptionField.getText().trim());

            if (tDClient.upsertSMSAlert(sMSTemplate))
            {
                showSmsAlert(sMSTemplate.getTemplateId());
                JOptionPane.showMessageDialog(PHMain.phFrame, "Alert saved successfully.");
            }
            else
            {
                JOptionPane.showMessageDialog(PHMain.phFrame, "Failed to save Alert. Please refer to log for more details.", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_saveButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_findButtonActionPerformed
    {//GEN-HEADEREND:event_findButtonActionPerformed
        // TODO add your handling code here:
        searchAlert();
    }//GEN-LAST:event_findButtonActionPerformed

    private void findFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_findFieldActionPerformed
    {//GEN-HEADEREND:event_findFieldActionPerformed
        // TODO add your handling code here:
        findButton.doClick();
    }//GEN-LAST:event_findFieldActionPerformed

    private void templateIDFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_templateIDFieldFocusLost
    {//GEN-HEADEREND:event_templateIDFieldFocusLost
        // TODO add your handling code here:
        if (templateIDField.getText().trim().length() > 0)
        {
            verifyAlert();
        }
    }//GEN-LAST:event_templateIDFieldFocusLost

    private void chargeLedgerFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_chargeLedgerFieldFocusLost
    {//GEN-HEADEREND:event_chargeLedgerFieldFocusLost
        if (chargeLedgerField.getText().trim().length() > 0)
        {
            verifyAccount(chargeLedgerField.getText(), chargeLedgerField);
        }
    }//GEN-LAST:event_chargeLedgerFieldFocusLost

    private void currencyBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_currencyBoxActionPerformed
    {//GEN-HEADEREND:event_currencyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyBoxActionPerformed

    private void chargeAmtFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_chargeAmtFieldFocusLost
    {//GEN-HEADEREND:event_chargeAmtFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeAmtFieldFocusLost

    private void taxLedgerFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_taxLedgerFieldFocusLost
    {//GEN-HEADEREND:event_taxLedgerFieldFocusLost
        if (taxLedgerField.getText().trim().length() > 0)
        {
            verifyAccount(taxLedgerField.getText(), taxLedgerField);
        }
    }//GEN-LAST:event_taxLedgerFieldFocusLost

    private void taxAmtFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_taxAmtFieldFocusLost
    {//GEN-HEADEREND:event_taxAmtFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_taxAmtFieldFocusLost

    private void taxPercFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_taxPercFieldFocusLost
    {//GEN-HEADEREND:event_taxPercFieldFocusLost
        // TODO add your handling code here:
        if (taxPercField.getText().equals(""))
        {
            taxAmtField.setText("0");
        }
        else
        {
            BigDecimal taxAmt = new BigDecimal(chargeAmtField.getText()).multiply(new BigDecimal(taxPercField.getText())).divide(BigDecimal.TEN.multiply(BigDecimal.TEN));
            taxAmtField.setText(String.valueOf(taxAmt));
        }
    }//GEN-LAST:event_taxPercFieldFocusLost

    private void messageTemplateAreaFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_messageTemplateAreaFocusLost
    {//GEN-HEADEREND:event_messageTemplateAreaFocusLost

    }//GEN-LAST:event_messageTemplateAreaFocusLost

    private void messageTemplateAreaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_messageTemplateAreaMouseClicked
    {//GEN-HEADEREND:event_messageTemplateAreaMouseClicked
        // TODO add your handling code here:
        checkTemplatePopup(evt);
    }//GEN-LAST:event_messageTemplateAreaMouseClicked

    private void messageTemplateAreaMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_messageTemplateAreaMousePressed
    {//GEN-HEADEREND:event_messageTemplateAreaMousePressed
        // TODO add your handling code here:
        checkTemplatePopup(evt);
    }//GEN-LAST:event_messageTemplateAreaMousePressed

    private void messageTemplateAreaMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_messageTemplateAreaMouseReleased
    {//GEN-HEADEREND:event_messageTemplateAreaMouseReleased
        // TODO add your handling code here:
        checkTemplatePopup(evt);
    }//GEN-LAST:event_messageTemplateAreaMouseReleased

    private void insertPHButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_insertPHButtonActionPerformed
    {//GEN-HEADEREND:event_insertPHButtonActionPerformed
        // TODO add your handling code here:
        showPlaceHolderPopup();
    }//GEN-LAST:event_insertPHButtonActionPerformed

    private void acctNoPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acctNoPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_acctNoPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_acctNoPHMenuItemActionPerformed

    private void custNamePHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_custNamePHMenuItemActionPerformed
    {//GEN-HEADEREND:event_custNamePHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_custNamePHMenuItemActionPerformed

    private void currencyPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_currencyPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_currencyPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_currencyPHMenuItemActionPerformed

    private void amountPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_amountPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_amountPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_amountPHMenuItemActionPerformed

    private void chargePHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chargePHMenuItemActionPerformed
    {//GEN-HEADEREND:event_chargePHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_chargePHMenuItemActionPerformed

    private void descriptionPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_descriptionPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_descriptionPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_descriptionPHMenuItemActionPerformed

    private void datePHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_datePHMenuItemActionPerformed
    {//GEN-HEADEREND:event_datePHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_datePHMenuItemActionPerformed

    private void txnOriginatorPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txnOriginatorPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_txnOriginatorPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_txnOriginatorPHMenuItemActionPerformed

    private void daysPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_daysPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_daysPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_daysPHMenuItemActionPerformed

    private void accessCodePHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_accessCodePHMenuItemActionPerformed
    {//GEN-HEADEREND:event_accessCodePHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_accessCodePHMenuItemActionPerformed

    private void pinPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pinPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_pinPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_pinPHMenuItemActionPerformed

    private void balancePHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_balancePHMenuItemActionPerformed
    {//GEN-HEADEREND:event_balancePHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_balancePHMenuItemActionPerformed

    private void dueDatePHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dueDatePHMenuItemActionPerformed
    {//GEN-HEADEREND:event_dueDatePHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_dueDatePHMenuItemActionPerformed

    private void repayAmountPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_repayAmountPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_repayAmountPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_repayAmountPHMenuItemActionPerformed

    private void unpaidAmountPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_unpaidAmountPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_unpaidAmountPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_unpaidAmountPHMenuItemActionPerformed

    private void contraAcctNoPHMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_contraAcctNoPHMenuItemActionPerformed
    {//GEN-HEADEREND:event_contraAcctNoPHMenuItemActionPerformed
        // TODO add your handling code here:
        processPlaceHolderAction(evt);
    }//GEN-LAST:event_contraAcctNoPHMenuItemActionPerformed

    private void chargeDescFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_chargeDescFieldFocusLost
    {//GEN-HEADEREND:event_chargeDescFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeDescFieldFocusLost

    private void taxDescFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_taxDescFieldFocusLost
    {//GEN-HEADEREND:event_taxDescFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_taxDescFieldFocusLost

    private void alertTypePropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_alertTypePropertyChange
    {//GEN-HEADEREND:event_alertTypePropertyChange
        // TODO add your handling code here:


    }//GEN-LAST:event_alertTypePropertyChange

    private void alertTypeItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_alertTypeItemStateChanged
    {//GEN-HEADEREND:event_alertTypeItemStateChanged
        // TODO add your handling code here:
        switch (alertType.getSelectedItem().toString())
        {
            case "DR":
                templateIDField.setText("TDR");
                break;
            case "CR":
                templateIDField.setText("TCR");
                break;
            case "TFR":
                templateIDField.setText("TFR");
                break;
            case "TFR2":
                templateIDField.setText("TFR2");
                break;
            case "ENQ":
                templateIDField.setText("ENQ");
                break;
            case "BRD":
                templateIDField.setText("BRD");
                break;
            default:
                templateIDField.setText("");
                break;
        }
    }//GEN-LAST:event_alertTypeItemStateChanged

    private void verifyAccount(String glNumber, JComponent jComponent)
    {
        BalloonTipStyle edgedLook = new EdgedBalloonStyle(Color.CYAN, Color.BLUE);
      //  BalloonTipStyle edgedLook2 = new EdgedBalloonStyle(Color.RED, Color.RED);
        Object[][] glLedger = tDClient.verifyGLNumber(glNumber.substring(9));
        if (glLedger.length != 0)
        {
            BalloonTip myBalloonTip = new BalloonTip(jComponent, new JLabel(tDClient.capitalize(glLedger[0][0].toString())), edgedLook, BalloonTip.Orientation.RIGHT_BELOW, BalloonTip.AttachLocation.ALIGNED, 40, 20, false);
            TimingUtils.showTimedBalloon(myBalloonTip, 3000);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid or InActive Biller account!");
            // BalloonTip myBalloonTip = new BalloonTip(jComponent, new JLabel("Invalid GL or Inactive GL"), edgedLook2, BalloonTip.Orientation.RIGHT_BELOW, BalloonTip.AttachLocation.ALIGNED, 40, 20, true);
        }
    }

    private void checkTemplatePopup(MouseEvent e)
    {
        if (e.isPopupTrigger())
        {
            showPlaceHolderPopup();
        }
    }

    private void showPlaceHolderPopup()
    {
        try
        {
            Rectangle pos = messageTemplateArea.modelToView(messageTemplateArea.getCaretPosition());
            templatePopupMenu.show(messageTemplateArea, ((Double) pos.getX()).intValue(), ((Double) pos.getY()).intValue() + pos.height);
        }
        catch (BadLocationException ex)
        {
            ex.printStackTrace();
        }
    }

    private void processPlaceHolderAction(ActionEvent event)
    {
        String field = event.getActionCommand();
        switch (field)
        {
            case "Account Number":
                field = "{ACCTNO}";
                break;
            case "Contra Account Number":
                field = "{CONTRAACCT}";
                break;
            case "Customer Name":
                field = "{CUSTNAME}";
                break;
            case "Transaction Amount":
                field = "{TXNAMT}";
                break;
            case "Transaction Charge":
                field = "{CHARGE}";
                break;
            case "Transaction Description":
                field = "{TXNDESC}";
                break;
            case "Cleared Balance":
                field = "{CLRDBAL}";
                break;
            case "Transaction Date":
                field = "{TXNDATE}";
                break;
            case "Transaction Currency":
                field = "{CURRENCY}";
                break;
            case "Transaction Originator":
                field = "{ORIGINATOR}";
                break;
            case "Days Due or Days Past":
                field = "{DAYS}";
                break;
            case "Access Code":
                field = "{ACSCODE}";
                break;
            case "Loan Due Date":
                field = "{DUEDATE}";
                break;
            case "Repayment Amount":
                field = "{REPAYAMT}";
                break;
            case "Unpaid Amount":
                field = "{UNPAIDAMT}";
                break;
            case "Mobile PIN":
                field = "{PIN}";
                break;
        }
        String text = messageTemplateArea.getText();
        int carPos = messageTemplateArea.getCaretPosition();
        String tSp = "", lSp = text.substring(0, carPos).endsWith(" ") ? "" : " ";
        if (carPos < text.length())
        {
            tSp = text.substring(carPos).startsWith(" ") ? "" : " ";
        }
        messageTemplateArea.insert(lSp + field + tSp, carPos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accessCodePHMenuItem;
    private javax.swing.JMenuItem acctNoPHMenuItem;
    private javax.swing.JComboBox alertType;
    private javax.swing.JTree alertTypeTree;
    private javax.swing.JMenuItem amountPHMenuItem;
    private javax.swing.JMenuItem balancePHMenuItem;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox chargableBox;
    private javax.swing.JTextField chargeAmtField;
    private javax.swing.JTextField chargeDescField;
    private javax.swing.JTextField chargeLedgerField;
    private javax.swing.JMenuItem chargePHMenuItem;
    private javax.swing.JMenuItem contraAcctNoPHMenuItem;
    private javax.swing.JPanel currenciesPanel;
    private javax.swing.JComboBox currencyBox;
    private javax.swing.JMenuItem currencyPHMenuItem;
    private javax.swing.JMenuItem custNamePHMenuItem;
    private javax.swing.JTextField dateModifiedField;
    private javax.swing.JMenuItem datePHMenuItem;
    private javax.swing.JMenuItem daysPHMenuItem;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JMenuItem descriptionPHMenuItem;
    private javax.swing.JMenuItem dueDatePHMenuItem;
    private javax.swing.JComboBox findBox;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findField;
    private javax.swing.JButton insertPHButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea messageTemplateArea;
    private javax.swing.JTextField modifiedByField;
    private javax.swing.JComboBox moduleBox;
    private javax.swing.JMenuItem pinPHMenuItem;
    private javax.swing.JMenuItem repayAmountPHMenuItem;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox statusBox;
    private javax.swing.JTextField taxAmtField;
    private javax.swing.JTextField taxDescField;
    private javax.swing.JTextField taxLedgerField;
    private javax.swing.JTextField taxPercField;
    private javax.swing.JTextField templateIDField;
    private javax.swing.JPopupMenu templatePopupMenu;
    private javax.swing.JScrollPane templateScroller;
    private javax.swing.JScrollPane terminalsScroller;
    private javax.swing.JMenuItem txnOriginatorPHMenuItem;
    private javax.swing.JMenuItem unpaidAmountPHMenuItem;
    // End of variables declaration//GEN-END:variables

    private void verifyAlert()
    {
        String templateId = templateIDField.getText().trim();
        if (PHController.getSmsAlert().containsKey(templateId))
        {
            findField.setText(templateId);
            findBox.setSelectedIndex(0);
            searchAlert();
        }
    }

    public void searchAlert()
    {
        DefaultMutableTreeNode rootNode = ((DefaultMutableTreeNode) alertTypeTree.getModel().getRoot());
        DefaultMutableTreeNode newTerminal = new DefaultMutableTreeNode("Add Biller Code");

        rootNode.removeAllChildren();
        rootNode.add(newTerminal);

        boolean isAlertFound = false;
        for (SMSTemplate sTemplate : PHController.getSmsAlert().values())
        {
            if (findBox.getSelectedIndex() == 0 ? sTemplate.getTemplateId().endsWith(findField.getText().trim()) : sTemplate.getStatus().endsWith(findField.getText().trim()))
            {
                DefaultMutableTreeNode node = new DefaultMutableTreeNode(sTemplate);
                rootNode.add(node);

                if (!isAlertFound)
                {
                    alertTypeTree.setSelectionPath(new TreePath(node.getPath()));
                    isAlertFound = true;
                }
            }
        }

        terminalsScroller.getHorizontalScrollBar().setValue(0);
        terminalsScroller.getVerticalScrollBar().setValue(0);
        alertTypeTree.updateUI();
    }

    public void setAlertTree()
    {
        PHController.loadAlerts();
        DefaultMutableTreeNode smsAlertRootNode = ((DefaultMutableTreeNode) alertTypeTree.getModel().getRoot());
        DefaultMutableTreeNode newSmsAlert = new DefaultMutableTreeNode("Add Alert");

        smsAlertRootNode.removeAllChildren();
        smsAlertRootNode.add(newSmsAlert);

        PHController.getSmsAlert().values().stream().map((smsAlert) -> new DefaultMutableTreeNode(smsAlert)).forEach((node) ->
        {
            smsAlertRootNode.add(node);
        });

        terminalsScroller.getHorizontalScrollBar().setValue(0);
        terminalsScroller.getVerticalScrollBar().setValue(0);
        alertTypeTree.updateUI();
    }

    private void showSmsAlert(String ID)
    {
        findField.setText("");
        setAlertTree();

        DefaultMutableTreeNode rootNode = ((DefaultMutableTreeNode) alertTypeTree.getModel().getRoot());
        DefaultMutableTreeNode child = rootNode.getFirstLeaf();
        while (child != null)
        {
            if (child.getUserObject() instanceof SMSTemplate)
            {
                if (((SMSTemplate) child.getUserObject()).getTemplateId().equalsIgnoreCase(ID))
                {
                    alertTypeTree.setSelectionPath(new TreePath(child.getPath()));
                    alertTypeTree.updateUI();
                    return;
                }
            }
            child = child.getNextSibling();
        }
    }

}
