
package FILELoad;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FCMB", targetNamespace = "http://elma.bz/", wsdlLocation = "http://192.168.186.56:5000/CustomerDataUpload.asmx?wsdl")
public class FCMB
    extends Service
{

    private final static URL FCMB_WSDL_LOCATION;
    private final static WebServiceException FCMB_EXCEPTION;
    private final static QName FCMB_QNAME = new QName("http://elma.bz/", "FCMB");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.186.56:5000/CustomerDataUpload.asmx?wsdl");           
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCMB_WSDL_LOCATION = url;
        FCMB_EXCEPTION = e;
    }

    public FCMB() {
        super(__getWsdlLocation(), FCMB_QNAME);
    }

    public FCMB(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCMB_QNAME, features);
    }

    public FCMB(URL wsdlLocation) {
        super(wsdlLocation, FCMB_QNAME);
    }

    public FCMB(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCMB_QNAME, features);
    }

    public FCMB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCMB(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCMBSoap
     */
    @WebEndpoint(name = "FCMBSoap")
    public FCMBSoap getFCMBSoap() {
        return super.getPort(new QName("http://elma.bz/", "FCMBSoap"), FCMBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCMBSoap
     */
    @WebEndpoint(name = "FCMBSoap")
    public FCMBSoap getFCMBSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://elma.bz/", "FCMBSoap"), FCMBSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns FCMBSoap
     */
    @WebEndpoint(name = "FCMBSoap12")
    public FCMBSoap getFCMBSoap12() {
        return super.getPort(new QName("http://elma.bz/", "FCMBSoap12"), FCMBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCMBSoap
     */
    @WebEndpoint(name = "FCMBSoap12")
    public FCMBSoap getFCMBSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://elma.bz/", "FCMBSoap12"), FCMBSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns FCMBHttpGet
     */
    @WebEndpoint(name = "FCMBHttpGet")
    public FCMBHttpGet getFCMBHttpGet() {
        return super.getPort(new QName("http://elma.bz/", "FCMBHttpGet"), FCMBHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCMBHttpGet
     */
    @WebEndpoint(name = "FCMBHttpGet")
    public FCMBHttpGet getFCMBHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://elma.bz/", "FCMBHttpGet"), FCMBHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns FCMBHttpPost
     */
    @WebEndpoint(name = "FCMBHttpPost")
    public FCMBHttpPost getFCMBHttpPost() {
        return super.getPort(new QName("http://elma.bz/", "FCMBHttpPost"), FCMBHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCMBHttpPost
     */
    @WebEndpoint(name = "FCMBHttpPost")
    public FCMBHttpPost getFCMBHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://elma.bz/", "FCMBHttpPost"), FCMBHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCMB_EXCEPTION!= null) {
            throw FCMB_EXCEPTION;
        }
        return FCMB_WSDL_LOCATION;
    }

}
