
package FILELoad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FCMBHttpPost", targetNamespace = "http://elma.bz/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCMBHttpPost {


    /**
     * 
     * @param accountID
     * @param ourBranchID
     * @param clientID
     * @param productID
     * @param groupID
     * @param accountType
     * @param header
     * @param titleOfAccount
     * @param atmCardNumber
     * @param updated
     * @param nrc
     * @param accountIDOld
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CustomerData")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String customerData(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "OurBranchID")
        String ourBranchID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "GroupID")
        String groupID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ClientID")
        String clientID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID")
        String accountID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TitleOfAccount")
        String titleOfAccount,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ProductID")
        String productID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountType")
        String accountType,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NRC")
        String nrc,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ATMCardNumber")
        String atmCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Updated")
        String updated,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Header")
        String header,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID_Old")
        String accountIDOld);

    /**
     * 
     * @param lastName
     * @param branchID
     * @param typeOfID
     * @param address
     * @param city
     * @param mobileNumber
     * @param maximumAmount
     * @param idNumber
     * @param title
     * @param firstName
     * @param accountID
     * @param customerType
     * @param eMailID
     * @param noOfTransactions
     * @param header
     * @param middleName
     * @param transactionLimit
     * @param currencyID
     * @param updated
     * @param cardNumber
     * @param accountIDOld
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MobileRegistration")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String mobileRegistration(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FirstName")
        String firstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MiddleName")
        String middleName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LastName")
        String lastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MobileNumber")
        String mobileNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Address")
        String address,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "EMailID")
        String eMailID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "City")
        String city,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID")
        String accountID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "BranchID")
        String branchID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MaximumAmount")
        String maximumAmount,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TransactionLimit")
        String transactionLimit,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "IDNumber")
        String idNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NoOfTransactions")
        String noOfTransactions,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title")
        String title,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TypeOfID")
        String typeOfID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardNumber")
        String cardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CurrencyID")
        String currencyID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CustomerType")
        String customerType,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Updated")
        String updated,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Header")
        String header,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID_Old")
        String accountIDOld);

    /**
     * 
     * @param lastName
     * @param branchID
     * @param typeOfID
     * @param address
     * @param city
     * @param mobileNumber
     * @param maximumAmount
     * @param idNumber
     * @param title
     * @param firstName
     * @param accountID
     * @param customerType
     * @param eMailID
     * @param noOfTransactions
     * @param header
     * @param middleName
     * @param transactionLimit
     * @param currencyID
     * @param updated
     * @param cardNumber
     * @param accountIDOld
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MobileMigration")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String mobileMigration(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FirstName")
        String firstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MiddleName")
        String middleName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LastName")
        String lastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MobileNumber")
        String mobileNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Address")
        String address,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "EMailID")
        String eMailID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "City")
        String city,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID")
        String accountID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "BranchID")
        String branchID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MaximumAmount")
        String maximumAmount,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TransactionLimit")
        String transactionLimit,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "IDNumber")
        String idNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NoOfTransactions")
        String noOfTransactions,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title")
        String title,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TypeOfID")
        String typeOfID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardNumber")
        String cardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CurrencyID")
        String currencyID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CustomerType")
        String customerType,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Updated")
        String updated,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Header")
        String header,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID_Old")
        String accountIDOld);

    /**
     * 
     * @param accountID
     * @param reason
     * @param mobileNumber
     * @param header
     * @param extraParams
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MobileDeregistration")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String mobileDeregistration(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MobileNumber")
        String mobileNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID")
        String accountID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Reason")
        String reason,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtraParams")
        String extraParams,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Header")
        String header);

    /**
     * 
     * @param accountID
     * @param clientID
     * @param productID
     * @param actualBalance
     * @param header
     * @param allowDeposit
     * @param titleOfAccount
     * @param nrc
     * @param accountIDOld
     * @param availableBalance
     * @param status
     * @param allowWithdrawal
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OfllineBalances")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String ofllineBalances(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ClientID")
        String clientID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID")
        String accountID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TitleOfAccount")
        String titleOfAccount,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ProductID")
        String productID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ActualBalance")
        String actualBalance,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AvailableBalance")
        String availableBalance,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Status")
        String status,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AllowDeposit")
        String allowDeposit,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AllowWithdrawal")
        String allowWithdrawal,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NRC")
        String nrc,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Header")
        String header,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID_Old")
        String accountIDOld);

    /**
     * 
     * @param agentID
     * @param postalADDRESS
     * @param mobilePHONE
     * @param officePHONE
     * @param emailADDRESS
     * @param businessNAME
     * @param codCUSTNAILID
     * @param physicalADDRESS
     * @param branchCODE
     * @param productCODE
     * @param agentACCOUNT
     * @param header
     * @param currency
     * @param businessTYPE
     * @param accountBAL
     * @param updated
     * @param nrc
     * @param accountIDOld
     * @param contactPERSON
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AgentData")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String agentData(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PRODUCT_CODE")
        String productCODE,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CURRENCY")
        String currency,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "BRANCH_CODE")
        String branchCODE,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "COD_CUST_NAIL_ID")
        String codCUSTNAILID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AGENT_ID")
        String agentID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AGENT_ACCOUNT")
        String agentACCOUNT,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ACCOUNT_BAL")
        String accountBAL,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "BUSINESS_NAME")
        String businessNAME,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "BUSINESS_TYPE")
        String businessTYPE,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PHYSICAL_ADDRESS")
        String physicalADDRESS,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "POSTAL_ADDRESS")
        String postalADDRESS,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CONTACT_PERSON")
        String contactPERSON,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MOBILE_PHONE")
        String mobilePHONE,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "OFFICE_PHONE")
        String officePHONE,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "EMAIL_ADDRESS")
        String emailADDRESS,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Updated")
        String updated,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "header")
        String header,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NRC")
        String nrc,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AccountID_Old")
        String accountIDOld);

    /**
     * 
     * @param messageText
     * @param mobileNumber
     * @param messageID
     * @param header
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OrbitSMS")
    @WebResult(name = "string", targetNamespace = "http://elma.bz/", partName = "Body")
    public String orbitSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MessageID")
        String messageID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MessageText")
        String messageText,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MobileNumber")
        String mobileNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "header")
        String header);

}
